name: Build Rindo

on:
  workflow_call:
  # Make this a reusable workflow, no value needed
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  build_core:
    name: Core
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Core Build
        run: npm run build -- --ci
        shell: bash

      - name: Upload Build Artifacts
        uses: ./.github/workflows/actions/upload-archive
        with:
          name: rindo-core
          output: rindo-core-build.zip
          paths: build cli compiler dependencies.json dev-server internal mock-doc scripts screenshot sys testing
