name: CI

on:
  push:
    branches:
      - 'main'
      - 'v3.0.0-dev'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_core:
    name: Build
    uses: ./.github/workflows/build.yml

  lint_and_format:
    name: Lint and Format
    uses: ./.github/workflows/lint-and-format.yml
