name: esbuild CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_core:
    name: Build
    uses: ./.github/workflows/build-esbuild.yml
