# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Rindo to Github Packages

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    name: Publish Rindo (Production)
    strategy:
      fail-fast: false
      matrix:
        node: ['16']
        os: ['ubuntu-latest']
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: |
          npm ci \
          && npm run install.jest

        shell: bash

      - name: Core Build
        run: npm run build -- --ci
        shell: bash

      - name: Publish to Github Packages
        run: npm publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{secrets.FAMIBOT_GITHUB_TOKEN}}
